---
# tasks file for perfsonar-psconfig-web-admin

- name: Install Docker Python modules
  tags: [ 'ps::install' ]
  pip:
    name: docker
    state: latest

- name: create docker config directory "{{ perfsonar_pwa_docker_config_dir }}"
  tags: [ 'ps::config' ]
  file:
    name: "{{ perfsonar_pwa_docker_config_dir }}"
    state: directory

- name: docker config template in "{{ perfsonar_pwa_docker_config_dir }}"
  tags: [ 'ps::config' ]
  template:
    src: daemon.json
    dest: "{{ perfsonar_pwa_docker_config_dir }}"

- name: install pwa default configs
  tags: [ 'ps::config' ]
  unarchive:
    src: https://github.com/perfsonar/psconfig-web/raw/master/deploy/docker/pwa.sample.tar.gz
    dest: /etc
    remote_src: yes

- name: add FQDN to pwa config files
  tags: [ 'ps::config' ]
  replace:
    path: "{{ item }}"
    regexp: '<pwa_hostname>'
    replace: "{{ perfsonar_pwa_fqdn }}"
  with_items:
    - /etc/pwa/index.js
    - /etc/pwa/auth/index.js

- name: add email address to pwa config files
  tags: [ 'ps::config' ]
  replace:
    path: "{{ item }}"
    regexp: '<email_address>'
    replace: "{{ perfsonar_pwa_email_address }}"
  with_items:
    - /etc/pwa/auth/index.js
  when: perfsonar_pwa_email_address != "<email_address>"

- name: remove --selinux-enabled option from /etc/sysconfig/docker
  tags: [ 'ps::config' ]
  replace:
    path: /etc/sysconfig/docker
    regexp: '--selinux-enabled'
    replace: ''
  when: perfsonar_pwa_selinux_disable

- name: create cert directory "{{ perfsonar_pwa_cert_path }}"
  tags: [ 'ps::config' ]
  file:
    name: "{{ perfsonar_pwa_cert_path }}"
    state: directory

# TODO convert this to Ansible modules
- name: Generate self-signed ssl certificate
  tags: [ 'ps::config' ]
  command: "openssl req -x509 -nodes -batch -days 1000 -newkey rsa:2048 -keyout {{ perfsonar_pwa_cert_path }}/key.pem -out {{ perfsonar_pwa_cert_path }}/cert.pem"

- name: copy cert.pm to trusted.pm
  tags: [ 'ps::config' ]
  copy:
    remote_src: true
    src: "{{ perfsonar_pwa_cert_path }}/cert.pem"
    dest: "{{ perfsonar_pwa_cert_path }}/trusted.pem"

### TODO: LOGROTATE

### TODO: INTEGRATE WITH OTHER WEB APPS
### https://docs.perfsonar.net/pwa_running_alongside

### TODO: SSL HOST CERTIFICATES

- name: enable and start docker 
  tags: [ 'ps::running' ]
  systemd:
    name: docker
    enabled: yes
    state: started

- name: create docker network {{ perfsonar_pwa_docker_network }}
  tags: [ 'ps::running' ]
  docker_network:
    name: "{{ perfsonar_pwa_docker_network }}"

- name: create pwa data directory
  tags: [ 'ps::config' ]
  file:
    name: "{{ perfsonar_pwa_docker_data_root }}/data"
    state: directory

- name: create pwa data/mongo directory
  tags: [ 'ps::config' ]
  file:
    name: "{{ perfsonar_pwa_docker_data_root }}/data/mongo"
    state: directory

- name: create mongo db Docker container
  tags: [ 'ps::running' ]
  docker_container:
    name: mongo
    image: mongo
    pull: "{{ perfsonar_pwa_docker_pull_image | default('no') }}"
    restart: yes
    detach: yes
    networks: 
      - name: "{{ perfsonar_pwa_docker_network }}"
    volumes: 
      - "{{ perfsonar_pwa_docker_data_root }}/data/mongo:/data/db"

- name: run SCA auth service Docker container
  tags: [ 'ps::running' ]
  docker_container:
    name: sca-auth
    image: perfsonar/sca-auth
    pull: "{{ perfsonar_pwa_docker_pull_image | default('no') }}"
    restart: yes
    detach: yes
    networks: 
      - name: "{{ perfsonar_pwa_docker_network }}"
    volumes: 
      - /etc/pwa/auth:/app/api/config
      - /usr/local/data/auth:/db

- name: run PWA's main UI/API Docker container
  tags: [ 'ps::running' ]
  docker_container:
    name: pwa-admin1
    image: perfsonar/pwa-admin
    pull: "{{ perfsonar_pwa_docker_pull_image | default('no') }}"
    restart: yes
    detach: yes
    networks: 
      - name: "{{ perfsonar_pwa_docker_network }}"
    volumes: 
      - /etc/pwa:/app/api/config:ro

- name: run meshconfig publisher Docker container
  tags: [ 'ps::running' ]
  docker_container:
    name: pwa-pub1
    image: perfsonar/pwa-pub
    pull: "{{ perfsonar_pwa_docker_pull_image | default('no') }}"
    restart: yes
    detach: yes
    networks: 
      - name: "{{ perfsonar_pwa_docker_network }}"
    volumes: 
      - /etc/pwa:/app/api/config:ro

- name: run nginx Docker container
  tags: [ 'ps::running' ]
  docker_container:
    name: nginx
    image: nginx
    pull: "{{ perfsonar_pwa_docker_pull_image | default('no') }}"
    restart: yes
    detach: yes
    networks: 
      - name: "{{ perfsonar_pwa_docker_network }}"
    volumes: 
      - /etc/pwa/shared:/shared:ro
      - /etc/pwa/nginx:/etc/nginx:ro
      - /etc/pwa/auth:/certs:ro
    published_ports:
      - 80:80
      - 443:443
      - 9443:9443

- name: manage PWA local users
  tags: [ 'ps::pwa_users' ]
  include: pwa_users.yml

- name: meta end play
  meta: end_play

