---
# pwa_passwd_reset.yml

- name: perfSONAR ps-config-web-admin interactive password reset
  hosts: ps-psconfig-web-admin
  vars_prompt:
    - name: username
      deleagete to: localhost
      prompt: "Reset PWA password for username"
      private: no

    - name: password
      deleagete to: localhost
      confirm: yes
      prompt: "New password"

  tasks:
    - name: reset PWA password
      command:
        argv:
          - docker
          - exec
          - -it
          - sca-auth
          - pwa_auth
          - setpass
          - --username
          - "{{ username }}"
          - --password
          - "{{ password }}"
